services:
  frontend:
    build:
      context: ./Frontend/LogEngine-front
    container_name: "${FRONTEND_HOST}"
    ports:
      - "${FRONTEND_PORT}:80"
    environment:
      - API_HOST=${API_HOST}
      - API_PORT=${API_PORT}
    depends_on:
    - api
  api:
    build:
      context: ./API
    container_name: "${API_HOST}"
    ports:
      - "${API_PORT}:${API_PORT}"
    environment:
      - OPENSEARCH_HOST=${OPENSEARCH_HOST}
      - OPENSEARCH_PORT=${OPENSEARCH_PORT}
      - API_PORT=${API_PORT}
      - FRONTEND_HOST=${FRONTEND_HOST}
      - FRONTEND_PORT=${FRONTEND_PORT}
    depends_on:
      - opensearch-node
  opensearch-node:
    image: opensearchproject/opensearch:2.11.1
    container_name: "${OPENSEARCH_HOST}"
    environment:
      - discovery.type=single-node
      - DISABLE_SECURITY_PLUGIN=true
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m"
    ports:
      - "${OPENSEARCH_PORT}:${OPENSEARCH_PORT}"
      - "9600:9600"
    volumes:
      - opensearch_volume:/usr/share/opensearch/data

volumes:
  opensearch_volume:
